version: "3"
services:
  client:
    depends_on: 
      - api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  api:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"